/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { TimeNode, TimelineConfig } from './types';

// The timeline spans from 2026-01-01 to 2030-12-31 (5 Years)
// Today is exactly 2026-07-04
export const DEFAULT_CONFIG: TimelineConfig = {
  startDate: '2026-01-01',
  endDate: '2030-12-31',
  todayDate: '2026-07-04',
};

export const INITIAL_NODES: TimeNode[] = [
  {
    id: 'node-1',
    title: 'Lancement du SaaS MVP',
    description: 'Mise en ligne de la version alpha de notre plateforme de productivité.',
    date: '2026-01-15',
    type: 'project',
    category: 'Professional',
    notes: 'Observations : Le lancement a été stressant mais réussi. Nous avons obtenu nos 100 premiers utilisateurs en moins de 48 heures. Retours majeurs : simplifier l\'onboarding et corriger les bugs de l\'éditeur de texte en temps réel. La discipline de fer de l\'équipe a payé.',
    completed: true,
  },
  {
    id: 'node-2',
    title: 'Financement d\'amorçage validé',
    description: 'Levée de fonds de 150k€ auprès de business angels locaux.',
    date: '2026-02-28',
    type: 'milestone',
    category: 'Financial',
    notes: 'Observations : Un parcours du combattant de 3 mois. Les pitches devant 12 jurys différents ont permis d\'affiner notre proposition de valeur. Cet argent va nous permettre de recruter deux développeurs seniors et d\'accélérer sur le marketing.',
    completed: true,
  },
  {
    id: 'node-3',
    title: 'Semi-Marathon de Paris',
    description: 'Course complétée en moins de 1h45.',
    date: '2026-04-10',
    type: 'milestone',
    category: 'Health',
    notes: 'Observations : Temps final : 1h42m15s. Une préparation rigoureuse de 12 semaines (3 entraînements par semaine). Leçon de vie : la régularité bat l\'intensité à chaque fois. Les 5 derniers kilomètres ont été très mentaux.',
    completed: true,
  },
  {
    id: 'node-4',
    title: 'Acquisition de l\'appartement',
    description: 'Signature de l\'acte authentique pour un investissement locatif à Lyon.',
    date: '2026-05-18',
    type: 'project',
    category: 'Financial',
    notes: 'Observations : Excellent rendement locatif visé (6.2% net). Travaux de rénovation prévus sur 3 semaines. Gestion déléguée pour minimiser la charge mentale. La négociation sur le taux d\'intérêt s\'est faite au centième de point près !',
    completed: true,
  },
  {
    id: 'node-5',
    title: 'Bilan de santé & Jeûne',
    description: 'Expérience de jeûne hydrique de 3 jours pour détoxifier l\'organisme.',
    date: '2026-06-05',
    type: 'observation',
    category: 'Health',
    notes: 'Observations : Incroyable clarté mentale à partir du deuxième jour. Le plus dur n\'est pas la faim physique, mais l\'habitude sociale de manger. Poids stabilisé, énergie débordante retrouvée. À refaire deux fois par an.',
    completed: true,
  },
  {
    id: 'node-6',
    title: 'Design System Unifié V1.0',
    description: 'Création d\'une charte graphique et de composants web réutilisables.',
    date: '2026-06-25',
    type: 'project',
    category: 'Professional',
    notes: 'Observations : Refonte totale de notre UI. Les gains en vitesse d\'intégration sont de l\'ordre de 40% sur les nouvelles pages. Figma et Tailwind forment le duo parfait. La cohérence visuelle rassure énormément nos clients B2B.',
    completed: true,
  },
  {
    id: 'node-7',
    title: 'Bilan de mi-parcours & Pivot',
    description: 'Concentration de l\'effort produit exclusivement sur le segment des PME.',
    date: '2026-07-01',
    type: 'observation',
    category: 'Growth',
    notes: 'Observations : Analyse des données : les clients individuels ont un taux d\'attrition (churn) too élevé (8%). En revanche, les équipes de PME restent fidèles et achètent plus de licences. Ce recentrage va nous permettre d\'atteindre la rentabilité cette année.',
    completed: true,
  },
  // ----- PRESENT IS 2026-07-04 -----
  {
    id: 'node-8',
    title: 'Certification AI Architect',
    description: 'Formation approfondie sur l\'intégration des LLM et des modèles prédictifs.',
    date: '2026-11-15',
    type: 'project',
    category: 'Professional',
    notes: 'Plan d\'action : Valider les 4 modules sur Coursera / Google Cloud. Projet pratique : créer un agent de tri automatique des tickets clients s\'appuyant sur Gemini Pro. Objectif : gain de temps de 50% pour le support.',
    completed: false,
  },
  {
    id: 'node-9',
    title: 'Lancement Commercial Europe',
    description: 'Traduction, localisation et campagnes publicitaires ciblées.',
    date: '2027-04-10',
    type: 'project',
    category: 'Professional',
    notes: 'Projection : Recrutement de deux country managers à mi-temps. Objectif de 50 comptes d\'entreprises par pays d\'ici la fin de l\'année. Partenariats stratégiques avec des influenceurs tech locaux.',
    completed: false,
  },
  {
    id: 'node-10',
    title: 'Liberté Financière - Étape 1',
    description: 'Atteinte d\'un portefeuille d\'actifs diversifiés générant 1000€/mois de passif.',
    date: '2027-10-30',
    type: 'milestone',
    category: 'Financial',
    notes: 'Stratégie : Réinvestissement systématique des dividendes, versement mensuel programmé sur des ETF mondiaux, et recherche d\'un second bien immobilier à crédit.',
    completed: false,
  },
  {
    id: 'node-11',
    title: 'Retraite de Yoga & Méditation',
    description: 'Séjour de 10 jours de silence (Vipassana) en Asie du Sud-Est.',
    date: '2028-03-12',
    type: 'milestone',
    category: 'Growth',
    notes: 'Objectif : Prendre du recul total. Se déconnecter entièrement des écrans et du travail pour stimuler la créativité profonde et réaligner mes valeurs de vie à long terme.',
    completed: false,
  },
  {
    id: 'node-12',
    title: 'Refonte Architecture Cloud',
    description: 'Migration vers un hébergement neutre en carbone et plus performant.',
    date: '2028-08-22',
    type: 'project',
    category: 'Professional',
    notes: 'Objectifs techniques : Réduire les coûts d\'infrastructure de 30% et le temps de réponse de l\'API à moins de 80ms globalement. Valoriser notre démarche écoresponsable.',
    completed: false,
  },
  {
    id: 'node-13',
    title: 'Publication d\'un Livre Blanc',
    description: 'Partager 5 ans de retours d\'expérience sur la création de produits digitaux éthiques.',
    date: '2029-01-15',
    type: 'project',
    category: 'Personal',
    notes: 'Structure : 10 chapitres synthétisant nos plus grandes erreurs, nos victoires méthodologiques et une vision prospective de l\'IA au service de l\'humain. Publication autonome ou éditeur spécialisé.',
    completed: false,
  },
  {
    id: 'node-14',
    title: 'Vision 4 Ans : Leader Éco',
    description: 'Consécration de notre vision : 1 million d\'utilisateurs actifs mensuels.',
    date: '2029-06-01',
    type: 'milestone',
    category: 'Growth',
    notes: 'Célébration du chemin parcouru depuis 2026. Transition vers un rôle de mentor pour les nouveaux entrepreneurs, tout en gardant un équilibre parfait entre vie professionnelle et santé physique/mentale.',
    completed: false,
  },
  {
    id: 'node-15',
    title: 'Bilan Final des 4 Ans de Vision',
    description: 'Analyse rétrospective globale de la période 2026-2029.',
    date: '2029-11-15',
    type: 'milestone',
    category: 'Growth',
    notes: 'Objectif : Faire le bilan de toutes les étapes de la vision, valider les apprentissages et définir les objectifs de la prochaine décennie.',
    completed: false,
  },
  {
    id: 'node-16',
    title: 'Fonds de Dotation Impact & Éco',
    description: 'Lancement d\'un programme de subventions pour les jeunes porteurs de projets écoresponsables.',
    date: '2030-04-20',
    type: 'project',
    category: 'Financial',
    notes: 'Vision 2030 : Allouer 5% des bénéfices du SaaS à des initiatives écologiques locales. Sélectionner 10 projets à fort impact pour un accompagnement technique gratuit et financier.',
    completed: false,
  },
  {
    id: 'node-17',
    title: 'Conférence de Transmission Annuelle',
    description: 'Keynote publique partageant le modèle de gouvernance participative et durable.',
    date: '2030-10-15',
    type: 'milestone',
    category: 'Growth',
    notes: 'Transmission : Présenter notre rapport d\'impact 5 ans après la fondation. Inspirer d\'autres créateurs de projets digitaux à adopter la sobriété numérique et l\'autonomie financière.',
    completed: false,
  }
];
